sudo: required
dist: trusty
language: python
python:
        - "3.2"
        - "3.3"
        - "3.4"
        - "3.5"
        - "3.6-dev"
        - "nightly"

addons:
        apt:
                sources:
                        - precise-pgdg-9.5
                packages:
                        - postgresql-9.5
                        - postgresql-contrib-9.5
                postgresql: "9.5"

install: 
        - "pip install -r requirements.txt"
        
before_script:
        - "sudo service postgresql start 9.5"
        - "ls -la /var/run/postgresql/"
        - psql -U postgres -f schema.sql

script: 
        - "pytest tests.py"
        - true
