sudo: required
dist: trusty
branches:
        only:
                - master
                - tests
language: python
python:
        - "3.3"
        - "3.4"
        - "3.5"
          #- "3.6-dev"
          #- "nightly"

addons:
        apt:
                sources:
                        - precise-pgdg-9.5
                packages:
                        - postgresql-9.5
                        - postgresql-contrib-9.5
                postgresql: "9.5"

install: 
        - "pip install -r requirements.txt"
        - "pip install pylint"
        
before_script:
        - "sudo service postgresql start 9.5"
        - "ls -la /var/run/postgresql/"
        - psql -U postgres -f schema.sql
        - "cp config.py.example config.py"


script: 
        - "pylint main.py gc.py stats.py"
        - "python3 main.py &"
        - "pytest tests.py"
