sudo: required
language: python
python:
        - "3.2"
        - "3.3"
        - "3.4"
        - "3.5"
        - "3.6-dev"
        - "nightly"

addons:
        apt:
                sources:
                        - precise-pgdg-9.5
                packages:
                        - postgresql-9.5
                        - postgresql-contrib-9.5
                postgresql: "9.5"

install: 
        - "pip install -r requirements.txt"
        
before_script:
        - psql -U postgres -f schema.sql

script: true
